---
- name: Add Kafka Group
  group:
    name: "{{ kafka_group }}"

- name: Add Kafka User
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    shell: /bin/bash
    home: "{{ kafka_install_dir }}"

- name: Create Kafka data directory
  file:
    path: "{{ kafka_data_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
